FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["ConsumerRedis.csproj", "./"]
RUN dotnet restore "ConsumerRedis.csproj"

COPY . .
RUN dotnet publish "ConsumerRedis.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/runtime:8.0 AS final
WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "ConsumerRedis.dll"]